// src/context/LanguageContext.jsx
import React, { createContext, useState, useContext, useCallback } from 'react';

// Translations – all UI text in English and Sinhala
const translations = {
  en: {
    appName: 'Neth-Sawan',
    tagline: 'Visual Hearing Assistant',
    sinhala: 'සිංහල',
    english: 'English',
    alertsOn: 'Alerts ON',
    alertsOff: 'Alerts OFF',
    roadSafeOn: 'Road Safe ON',
    roadSafeOff: 'Road Safe OFF',
    listening: 'LISTENING',
    stopped: 'STOPPED',
    guest: 'Guest',
    liveCaptionsSign: 'Live Captions & Sign Language',
    soundMonitor: 'Sound Monitor',
    soundWaveHistory: 'Sound Wave & History',
    roadSafetyActive: 'Road Safety Mode Active',
    listeningForVehicles: 'Listening for vehicles, horns, and sirens',
    startListening: 'Start Listening',
    stopListening: 'Stop Listening',
    speakClearly: 'Listening... Speak clearly and the text will appear here',
    trySaying: 'Try saying: "Hello, how are you?" or "I need help please"',
    copy: 'Copy',
    clear: 'Clear',
    braille: 'Braille',
    textSize: 'Text size:',
    signTranslator: 'Sign Language Translator',
    liveFromCaptions: 'Live from captions',
    speakWord: 'Speak a word like HELP, WATER, THANK YOU – I\'ll show the sign',
    commonSigns: 'Common Signs',
    howItWorks: 'How it works',
    howItWorksDesc: 'I listen to your speech and automatically show the matching sign language.',
    volumeLevel: 'Volume Level',
    loudSoundDetected: 'LOUD SOUND DETECTED!',
    unknownSound: 'Unknown sound',
    sensitivity: 'Sensitivity',
    recentSounds: 'Recent sounds:',
    normal: 'Normal',
    warning: 'Warning',
    critical: 'CRITICAL!',
    sosCenter: 'SOS Emergency Center',
    tapSOS: 'Tap the SOS button or use emergency numbers below',
    sos: 'SOS',
    police: 'Police',
    ambulance: 'Ambulance',
    emergencyInstructions: 'Emergency Instructions',
    redFlashing: 'Red Flashing Screen = Emergency detected or SOS activated',
    vibration: 'Phone Vibration = Alert being sent to your contacts',
    contactsNotify: 'Emergency Contacts = Will receive WhatsApp/SMS alerts',
    liveLocation: 'Live Location = Automatically shared with emergency contacts',
    home: 'මුල් පිටුව',
    homeEn: 'Home',
    aiVision: 'AI දෘෂ්ටිය',
    aiVisionEn: 'AI Vision',
    learnSigns: 'සංඥා ඉගෙන ගන්න',
    learnSignsEn: 'Learn Signs',
    alerts: 'ඇඟවීම්',
    alertsEn: 'Alerts',
    contacts: 'සම්බන්ධතා',
    contactsEn: 'Contacts',
    sosSide: 'හදිසි අවස්ථා',
    sosSideEn: 'SOS',
    roadMonitor: 'මාර්ග ආරක්ෂාව',
    roadMonitorEn: 'Road Monitor',
    accessibility: 'ප්‍රවේශ්‍යතාව',
    accessibilityEn: 'Accessibility',
    designedForDeaf: 'Designed for Deaf & Hard of Hearing',
    roadSafetyFeature: 'Road Safety Monitor',
    signLangFeature: 'Sign Language Translation',
    visualAlertsFeature: 'Visual Emergency Alerts',
    hapticFeature: 'Haptic Feedback',
    signOut: 'Sign Out',
    version: 'Neth-Sawan v3.0 - Deaf Accessibility Edition',
    emergencyContacts: 'Emergency Contacts',
    addContact: '+ Add Contact',
    fullName: 'Full Name *',
    phoneNumber: 'Phone Number',
    email: 'Email',
    relation: 'Relation',
    parent: 'Parent',
    spouse: 'Spouse',
    child: 'Child',
    sibling: 'Sibling',
    friend: 'Friend',
    caregiver: 'Caregiver',
    other: 'Other',
    notificationMethods: 'Notification Methods',
    whatsapp: 'WhatsApp',
    sms: 'SMS',
    phoneCall: 'Phone Call',
    desktop: 'Desktop',
    autoSendWhatsApp: 'Auto-send WhatsApp on emergency',
    saveContact: 'Save Contact',
    updateContact: 'Update Contact',
    cancel: 'Cancel',
    noContacts: 'No emergency contacts added yet.',
    addContactHint: 'Press "+ Add Contact" to add a contact. They will be notified during emergencies.',
    edit: 'Edit',
    remove: 'Remove',
    testAlert: 'Send test alert',
    notifications: 'Notifications',
    clearAll: 'Clear All',
    noNotifications: 'No notifications',
    emergencyAlertsHint: 'Emergency alerts will appear here.',
    viewLocation: 'View location',
    roadSafetyMonitor: 'Road Safety Monitor',
    startMonitoring: 'Start Road Safety Monitoring',
    stopMonitoring: 'Stop Monitoring',
    safetyTips: 'Safety Tips for Deaf Pedestrians',
    accessibilitySettings: 'Accessibility Settings',
    customizeExperience: 'Customize your experience for better visibility',
    fontSize: 'Font Size',
    small: 'Small',
    normal: 'Normal',
    large: 'Large',
    xlarge: 'X-Large',
    colorAccessibility: 'Color Accessibility',
    normalVision: 'Normal Vision',
    protanopia: 'Protanopia (Red-Blind)',
    deuteranopia: 'Deuteranopia (Green-Blind)',
    tritanopia: 'Tritanopia (Blue-Blind)',
    achromatopsia: 'Achromatopsia (Grayscale)',
    colorThemes: 'Color Themes',
    resetAll: 'Reset All Settings',
    dedicatedRoadSafety: 'Full‑screen detection of horns, sirens, engines – with direction & distance hints',
    noEmergencyAlerts: "You won't receive visual alerts or emergency flashes.",
    enableNow: 'Enable Now',
    notificationToggle: '🔕 Notification Toggle = Disable alerts when needed (top of screen)',
    loggedOut: 'Logged out',
    logoutFailed: 'Logout failed',
    guestModeActivated: 'Guest mode activated',
    guestSignedOut: 'Signed out from guest mode',
    switchedToSinhala: 'Switched to Sinhala',
    switchedToEnglish: 'Switched to English',
    user: 'User',
    guestMode: 'Guest Mode',
    loggedIn: 'Logged In',
    localDataOnly: 'Local Data Only',
    accessibilityReady: 'Accessibility Ready',
    words: 'words',
    characters: 'characters',
    pressStartToListen: 'Press "Start Listening" below, then speak to see captions',
    browserNotSupported: 'Your browser does not support Speech Recognition. Try Chrome, Edge, or Safari (iOS 14.3+).',
    mobileMicrophoneRequired: 'Mobile Microphone Required',
    mobileMicrophoneHint: 'When you tap "Start Listening", your browser will ask for microphone permission. Please allow it.',
    brailleTranslation: 'Braille Translation (Grade 1)',
    last200Braille: 'Last 200 characters shown in Braille',
    microphoneRequired: 'Microphone required',
    microphoneActive: 'Microphone is active',
    speakClearlyHint: 'Speak clearly at moderate pace',
    lastSpoken: 'Last spoken',
    tipsForBetterRecognition: 'Tips for better speech recognition',
    tipSpeakClearly: 'Speak clearly and at a normal pace',
    tipReduceNoise: 'Reduce background noise',
    tipHoldCloser: 'Hold phone closer to your mouth',
    tipShortPhrases: 'Speak in short phrases',
  },
  si: {
    appName: 'නෙත් සවන්',
    tagline: 'දෘශ්‍ය ශ්‍රවණ සහායක',
    sinhala: 'සිංහල',
    english: 'English',
    alertsOn: 'ඇඟවීම් ක්‍රියාත්මකයි',
    alertsOff: 'ඇඟවීම් අක්‍රියයි',
    roadSafeOn: 'මාර්ග ආරක්ෂාව ක්‍රියාත්මකයි',
    roadSafeOff: 'මාර්ග ආරක්ෂාව අක්‍රියයි',
    listening: 'සවන් දෙමින්',
    stopped: 'නවත්වා ඇත',
    guest: 'අමුත්තා',
    liveCaptionsSign: 'සජීවී පාඨ සහ සංඥා භාෂාව',
    soundMonitor: 'ශබ්ද නිරීක්ෂක',
    soundWaveHistory: 'ශබ්ද තරංග සහ ඉතිහාසය',
    roadSafetyActive: 'මාර්ග ආරක්ෂණ ප්‍රකාරය ක්‍රියාත්මකයි',
    listeningForVehicles: 'වාහන, හොරන් සහ සයිරන් සඳහා සවන් දෙමින්',
    startListening: 'සවන් දීම ආරම්භ කරන්න',
    stopListening: 'සවන් දීම නවත්වන්න',
    speakClearly: 'සවන් දෙමින්... පැහැදිලිව කතා කරන්න, පෙළ මෙහි දිස්වේ',
    trySaying: 'උත්සාහ කරන්න: "ආයුබෝවන්, කොහොමද?" හෝ "මට උදව් අවශ්‍යයි"',
    copy: 'පිටපත් කරන්න',
    clear: 'හිස් කරන්න',
    braille: 'බ්‍රේල්',
    textSize: 'අකුරු ප්‍රමාණය:',
    signTranslator: 'සංඥා භාෂා පරිවර්තකය',
    liveFromCaptions: 'සජීවී පාඨ වලින්',
    speakWord: 'HELP, WATER, THANK YOU වැනි වචනයක් කතා කරන්න – මම සංඥාව පෙන්වමි',
    commonSigns: 'පොදු සංඥා',
    howItWorks: 'මෙය ක්‍රියා කරන ආකාරය',
    howItWorksDesc: 'මම ඔබේ කතාවට සවන් දී ස්වයංක්‍රීයව ගැලපෙන සංඥා භාෂාව පෙන්වමි.',
    volumeLevel: 'ශබ්ද මට්ටම',
    loudSoundDetected: 'ඉහළ ශබ්දයක් අනාවරණය විය!',
    unknownSound: 'නොදන්නා ශබ්දය',
    sensitivity: 'සංවේදීතාව',
    recentSounds: 'මෑත ශබ්ද:',
    normal: 'සාමාන්‍ය',
    warning: 'අනතුරු ඇඟවීම',
    critical: 'අනතුරුදායකයි!',
    sosCenter: 'හදිසි SOS මධ්‍යස්ථානය',
    tapSOS: 'SOS බොත්තම ඔබන්න හෝ පහත හදිසි අංක භාවිතා කරන්න',
    sos: 'SOS',
    police: 'පොලිසිය',
    ambulance: 'ගිලන් රථය',
    emergencyInstructions: 'හදිසි උපදෙස්',
    redFlashing: 'රතු දැල්වෙන තිරය = හදිසි අවස්ථාවක් හෝ SOS සක්‍රිය කර ඇත',
    vibration: 'දුරකථන කම්පනය = ඔබේ සම්බන්ධතා වෙත අනතුරු ඇඟවීමක් යවමින්',
    contactsNotify: 'හදිසි සම්බන්ධතා = WhatsApp/SMS අනතුරු ඇඟවීම් ලැබෙනු ඇත',
    liveLocation: 'සජීවී ස්ථානය = හදිසි සම්බන්ධතා සමඟ ස්වයංක්‍රීයව බෙදාගනී',
    home: 'මුල් පිටුව',
    homeEn: 'Home',
    aiVision: 'AI දෘෂ්ටිය',
    aiVisionEn: 'AI Vision',
    learnSigns: 'සංඥා ඉගෙන ගන්න',
    learnSignsEn: 'Learn Signs',
    alerts: 'ඇඟවීම්',
    alertsEn: 'Alerts',
    contacts: 'සම්බන්ධතා',
    contactsEn: 'Contacts',
    sosSide: 'හදිසි අවස්ථා',
    sosSideEn: 'SOS',
    roadMonitor: 'මාර්ග ආරක්ෂාව',
    roadMonitorEn: 'Road Monitor',
    accessibility: 'ප්‍රවේශ්‍යතාව',
    accessibilityEn: 'Accessibility',
    designedForDeaf: 'බිහිරි සහ අසීරුවෙන් අසන පුද්ගලයන් සඳහා නිර්මාණය කර ඇත',
    roadSafetyFeature: 'මාර්ග ආරක්ෂණ මොනිටරය',
    signLangFeature: 'සංඥා භාෂා පරිවර්තනය',
    visualAlertsFeature: 'දෘශ්‍ය හදිසි ඇඟවීම්',
    hapticFeature: 'ස්පර්ශ ප්‍රතිපෝෂණය',
    signOut: 'පිටවන්න',
    version: 'නෙත් සවන් v3.0 - බිහිරි ප්‍රවේශ්‍යතා සංස්කරණය',
    emergencyContacts: 'හදිසි සම්බන්ධතා',
    addContact: '+ සම්බන්ධතාවක් එක් කරන්න',
    fullName: 'සම්පූර්ණ නම *',
    phoneNumber: 'දුරකථන අංකය',
    email: 'විද්‍යුත් තැපෑල',
    relation: 'ඥාතිත්වය',
    parent: 'දෙමාපිය',
    spouse: 'කලත්‍රයා',
    child: 'දරුවා',
    sibling: 'සහෝදර/සහෝදරිය',
    friend: 'මිතුරා',
    caregiver: 'රැකබලා ගන්නා',
    other: 'වෙනත්',
    notificationMethods: 'දැනුම්දීමේ ක්‍රම',
    whatsapp: 'WhatsApp',
    sms: 'කෙටි පණිවුඩය',
    phoneCall: 'දුරකථන ඇමතුම',
    desktop: 'පරිගණකය',
    autoSendWhatsApp: 'හදිසි අවස්ථාවකදී ස්වයංක්‍රීයව WhatsApp යවන්න',
    saveContact: 'සම්බන්ධතාව සුරකින්න',
    updateContact: 'යාවත්කාලීන කරන්න',
    cancel: 'අවලංගු කරන්න',
    noContacts: 'හදිසි සම්බන්ධතා කිසිවක් එක් කර නොමැත.',
    addContactHint: 'සම්බන්ධතාවක් එක් කිරීමට "+ සම්බන්ධතාවක් එක් කරන්න" ඔබන්න. හදිසි අවස්ථාවලදී ඔවුන්ට දැනුම් දෙනු ඇත.',
    edit: 'සංස්කරණය',
    remove: 'ඉවත් කරන්න',
    testAlert: 'පරීක්ෂණ අනතුරු ඇඟවීමක් යවන්න',
    notifications: 'දැනුම්දීම්',
    clearAll: 'සියල්ල හිස් කරන්න',
    noNotifications: 'දැනුම්දීම් නැත',
    emergencyAlertsHint: 'හදිසි ඇඟවීම් මෙහි දිස්වේ.',
    viewLocation: 'ස්ථානය බලන්න',
    roadSafetyMonitor: 'මාර්ග ආරක්ෂණ මොනිටරය',
    startMonitoring: 'මාර්ග ආරක්ෂණ මොනිටරය ආරම්භ කරන්න',
    stopMonitoring: 'මොනිටරය නවත්වන්න',
    safetyTips: 'බිහිරි පදිකයින් සඳහා ආරක්ෂණ ඉඟි',
    accessibilitySettings: 'ප්‍රවේශ්‍යතා සැකසුම්',
    customizeExperience: 'වඩා හොඳ දෘශ්‍යතාව සඳහා ඔබේ අත්දැකීම අභිරුචිකරණය කරන්න',
    fontSize: 'අකුරු ප්‍රමාණය',
    small: 'කුඩා',
    normal: 'සාමාන්‍ය',
    large: 'විශාල',
    xlarge: 'අති විශාල',
    colorAccessibility: 'වර්ණ ප්‍රවේශ්‍යතාව',
    normalVision: 'සාමාන්‍ය පෙනීම',
    protanopia: 'ප්‍රෝටනෝපියාව (රතු-අන්ධ)',
    deuteranopia: 'ඩොයුටෙරනෝපියාව (කොළ-අන්ධ)',
    tritanopia: 'ට්‍රයිටනෝපියාව (නිල්-අන්ධ)',
    achromatopsia: 'ඇක්‍රොමැටොප්සියාව (අළු පැහැ)',
    colorThemes: 'වර්ණ තේමා',
    resetAll: 'සියලු සැකසුම් යළි පිහිටුවන්න',
    dedicatedRoadSafety: 'හොරන්, සයිරන්, එන්ජින් හඳුනාගැනීම – දිශාව සහ දුර ඉඟි සමඟ',
    noEmergencyAlerts: 'ඔබට දෘශ්‍ය ඇඟවීම් හෝ හදිසි දැල්වීම් නොලැබේ.',
    enableNow: 'දැන් සක්‍රිය කරන්න',
    notificationToggle: '🔕 ඇඟවීම් ටොගලය = අවශ්‍ය විට අනතුරු ඇඟවීම් අක්‍රිය කරන්න (තිරයේ ඉහළින්)',
    loggedOut: 'පිටවීම සාර්ථකයි',
    logoutFailed: 'පිටවීම අසාර්ථකයි',
    guestModeActivated: 'අමුත්තන්ගේ ප්‍රකාරය සක්‍රිය කරන ලදී',
    guestSignedOut: 'අමුත්තන්ගේ ප්‍රකාරයෙන් පිටවිය',
    switchedToSinhala: 'සිංහලට මාරු විය',
    switchedToEnglish: 'ඉංග්‍රීසි වෙත මාරු විය',
    user: 'පරිශීලක',
    guestMode: 'අමුත්තන්ගේ ප්‍රකාරය',
    loggedIn: 'පුරනය වී ඇත',
    localDataOnly: 'දේශීය දත්ත පමණයි',
    accessibilityReady: 'ප්‍රවේශ්‍යතාව සූදානම්',
    words: 'වචන',
    characters: 'අක්ෂර',
    pressStartToListen: 'පහත "සවන් දීම ආරම්භ කරන්න" ඔබන්න, ඉන්පසු පාඨ බලන්න කතා කරන්න',
    browserNotSupported: 'ඔබගේ බ්‍රවුසරය හඬ හඳුනාගැනීමට සහාය නොදක්වයි. Chrome, Edge, හෝ Safari (iOS 14.3+) භාවිතා කරන්න.',
    mobileMicrophoneRequired: 'ජංගම මයික්‍රෆෝනය අවශ්‍යයි',
    mobileMicrophoneHint: 'ඔබ "සවන් දීම ආරම්භ කරන්න" තට්ටු කළ විට, ඔබගේ බ්‍රවුසරය මයික්‍රෆෝන අවසරය ඉල්ලයි. කරුණාකර එයට අවසර දෙන්න.',
    brailleTranslation: 'බ්‍රේල් පරිවර්තනය (1 ශ්‍රේණිය)',
    last200Braille: 'අවසන් අක්ෂර 200 බ්‍රේල් වලින් දක්වා ඇත',
    microphoneRequired: 'මයික්‍රෆෝනය අවශ්‍යයි',
    microphoneActive: 'මයික්‍රෆෝනය ක්‍රියාකාරීයි',
    speakClearlyHint: 'පැහැදිලිව මධ්‍යස්ථ වේගයෙන් කතා කරන්න',
    lastSpoken: 'අවසන් වරට කතා කළේ:',
    tipsForBetterSpeech: 'වඩා හොඳ හඬ හඳුනාගැනීම සඳහා ඉඟි',
    tipSpeakClearly: 'පැහැදිලිව සාමාන්‍ය වේගයෙන් කතා කරන්න',
    tipReduceNoise: 'පසුබිම් ශබ්දය අඩු කරන්න',
    tipHoldCloser: 'දුරකථනය ඔබේ මුඛයට සමීප කර ගන්න',
    tipShortPhrases: 'කෙටි වාක්‍ය වලින් කතා කරන්න',
  }
};

// Detect language from text (Sinhala Unicode range)
const detectLanguage = (text) => {
  if (!text) return null;
  if (/[\u0D80-\u0DFF]/.test(text)) return 'si';
  if (/[A-Za-z]/.test(text)) return 'en';
  return null;
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en');
  const [detectedTranscript, setDetectedTranscript] = useState('');

  const t = useCallback((key) => {
    return translations[language][key] || translations.en[key] || key;
  }, [language]);

  const updateLanguageFromTranscript = useCallback((transcriptText) => {
    setDetectedTranscript(transcriptText);
    const detected = detectLanguage(transcriptText);
    if (detected && detected !== language) {
      setLanguage(detected);
    }
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, updateLanguageFromTranscript }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);